kind: Service                             # Defines to create Service type Object
apiVersion: v1
metadata:
  name: fsservice
spec:
  ports:
    - port: 3000                               # Containers port exposed
      targetPort: 3000                     # Pods port
  selector:
    name: fsfunctions                    # Apply this service to any pods which has the specific label
  type: NodePort                       # Specifies the service type i.e ClusterIP or NodePort
